# Learning about Kalman filter / Background 

**Resources**

`Kalman Filter from Ground Up`; author Alex Becker; https://www.kalmanfilter.net

**Overview**

background infos from chapter 11

(as a preparation for nonlinear versions of the Kalman filter)

---

## Square Root of a Matrix

If a matrix $\mathbf{A}$ can be written as a product of two identical matrices $\mathbf{B}$

$$
\mathbf{A} = \mathbf{B} \cdot \mathbf{B}
$$

matrix $\mathbf{B}$ is called the square root of matrix $\mathbf{A}$.

The conditions on matrix $\mathbf{A}$ to make this possible will be explored later. But it is clear that the root is not a unique matrix.
If matrix $\mathbf{B}$ is a root of $\mathbf{A}$ then $-\mathbf{B}$ is also a root.

Obviously $\mathbf{A}$ and $\mathbf{B}$ must be square matrices with the same number of rows / columns.


---


## Special case: Square Root of Symmetric Matrix

If matrix $\mathbf{A} = \mathbf{A}^T;\ \in \mathbb{R}^{n \times n}$ then there exists the decomposition

$$
\mathbf{A} = \mathbf{U} \cdot \mathbf{D} \cdot \mathbf{U}^T
$$

This follows by applying the `singular value` decomposition to a symmetric matrix.

$\mathbf{U};\ \in \mathbb{R}^{n \times n}$ has orthonormal column vectors.

$\mathbf{D}; \in \mathbb{R}^{n \times n}$ is a diagonal matrix. The elements of the main diagonal are $\ge 0$.

Accordingly we have:

$$
\mathbf{U}^T \cdot \mathbf{U} = \mathbf{I}
$$

We now decompose diagonal matrix $\mathbf{D}$ into a product of two identical matrices denoted $\mathbf{D}^{1/2}$. 

$$
\mathbf{D} = \mathbf{D}^{1/2} \cdot \mathbf{D}^{1/2}
$$

For the root $\mathbf{A}^{1/2}$ of matrix $\mathbf{A}$ we get:

$$
\mathbf{A}^{1/2} = \mathbf{U} \cdot \mathbf{D}^{1/2} \cdot \mathbf{U}^T 
$$

**proof**

$$\begin{align}
\mathbf{A}^{1/2} \cdot \mathbf{A}^{1/2} &= \mathbf{U} \cdot \mathbf{D}^{1/2} \cdot \mathbf{U}^T \cdot \mathbf{U} \cdot \mathbf{D}^{1/2} \cdot \mathbf{U}^T \\
&= \mathbf{U} \cdot \mathbf{D}^{1/2} \cdot \underbrace{\left(\mathbf{U}^T \cdot \mathbf{U}\right)}_{\mathbf{I}} \cdot \mathbf{D}^{1/2} \cdot \mathbf{U}^T \\
&= \mathbf{U} \cdot \mathbf{D}^{1/2} \cdot \mathbf{D}^{1/2} \cdot \mathbf{U}^T \\
&= \mathbf{U} \cdot \mathbf{D} \cdot \mathbf{U}^T \\
&= \mathbf{A}
\end{align}
$$

From the equation $\mathbf{A}^{1/2} = \mathbf{U} \cdot \mathbf{D}^{1/2} \cdot \mathbf{U}^T$ we can show the symmetry of the square root matrix $\mathbf{A}^{1/2}$:

$$\begin{align}
\left(\mathbf{A}^{1/2}\right)^T &= \left(\mathbf{U} \cdot \mathbf{D}^{1/2} \cdot \mathbf{U}^T \right)^T \\
&= \mathbf{U} \cdot \left( \mathbf{U} \cdot \mathbf{D}^{1/2} \right)^T \\
&= \mathbf{U} \cdot \left(\mathbf{D}^{1/2} \right)^T \cdot \mathbf{U}^T \\
&= \mathbf{U} \cdot \mathbf{D}^{1/2} \cdot \mathbf{U}^T \\
\left(\mathbf{A}^{1/2}\right)^T &= \mathbf{A}^{1/2}
\end{align}
$$

## Cholesky Decomposition

If matrix $\mathbf{A}$ is positive definite than $\mathbf{A}$ can be decomposed into the product of a lower and upper triangular matrices.

$$
\mathbf{A} = \mathbf{L} \cdot \mathbf{L}^T
$$

$\mathbf{L}$ is a lower triangular square matrix. An example is shown here:

$$
\mathbf{L} = \left[\begin{array}{cccc}
l_{1,1} & 0 & 0 & 0 \\
l_{2,1} & l_{2,2} & 0 & 0 \\
l_{3,1} & l_{3,2} & l_{3,3} & 0 \\
l_{4,1} & l_{4,2} & l_{4,3} & l_{4,4}
\end{array}\right]
$$

In [2]:
# numerical example of Cholesky decomposition

import numpy as np

Amat = np. array ([[9 , -6, 3, 24] , [-6, 20, -22, -4], [3, -22, 30, -9], [24 ,
-4, -9, 99]])

# decomposition
Lmat = np.linalg.cholesky(Amat)


print(f"(Amat :\n{Amat}\n")
print(f"(Lmat :\n{Lmat}\n")
print(f"(Lmat @ Lmat.T :\n{Lmat @ Lmat.T}\n")

(Amat :
[[  9  -6   3  24]
 [ -6  20 -22  -4]
 [  3 -22  30  -9]
 [ 24  -4  -9  99]]

(Lmat :
[[ 3.  0.  0.  0.]
 [-2.  4.  0.  0.]
 [ 1. -5.  2.  0.]
 [ 8.  3. -1.  5.]]

(Lmat @ Lmat.T :
[[  9.  -6.   3.  24.]
 [ -6.  20. -22.  -4.]
 [  3. -22.  30.  -9.]
 [ 24.  -4.  -9.  99.]]

